name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # GitHub 저장소에서 코드를 가져옴

    - name: Install dependencies
      working-directory: ./mayo-client 
      run: npm install  # package.json을 기준으로 의존성 설치

    - name: Build
      working-directory: ./mayo-client 
      run: npm run build

    - name: SHOW AWS CLI VERSION
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true
      run: aws --version

    - name: Sync to S3 Bucket
      working-directory: ./mayo-client 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key ID (GitHub Secrets로 저장)
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key (GitHub Secrets로 저장)
        AWS_REGION: 'ap-northeast-2'  # AWS 리전
      run: | 
        aws s3 sync \
          build/ s3://mayo-web \
          --region ap-northeast-2 \
          --acl public-read \
          --delete
